# Git文件加速代理配置文件
# 此配置文件采用TOML格式，用于配置代理服务器的各项参数

# ==================== 服务器配置 ====================
[server]
# 服务器监听地址，0.0.0.0表示监听所有网络接口
# 如果只想本地访问，可以设置为127.0.0.1或localhost
host = "0.0.0.0" 

# 服务器监听端口号
# 默认8080，可根据需要修改，确保端口未被占用
port = 8080 

# 单个文件大小限制（单位：MB）
# 超过此大小的文件将被拒绝下载，防止服务器资源耗尽
# 2048MB = 2GB，可根据服务器性能和带宽调整
sizeLimit = 2048 # MB

# ==================== 日志配置 ====================
[log]
# 日志文件存储路径
# 建议使用绝对路径，确保目录存在且有写权限
# 日志文件会记录所有访问请求和错误信息
logFilePath = "./logs/ghproxy.log" 

# 单个日志文件最大大小（单位：MB）
# 超过此大小时会自动轮转（备份当前日志，创建新日志文件）
# 避免日志文件过大占用过多磁盘空间
maxLogSize = 5 # MB

# 日志级别
# debug: 调试信息（最详细）
# info: 一般信息（默认推荐）
# warn: 警告信息
# error: 错误信息
# none: 不记录日志
level = "info" # debug, info, warn, error, none

# ==================== 黑名单配置 ====================
[blacklist]
# 是否启用黑名单功能
# true: 启用，将阻止黑名单中的域名或IP访问
# false: 禁用黑名单功能
enabled = false

# 黑名单文件路径
# JSON格式文件，包含被禁止访问的域名、IP地址等
# 文件格式示例：["example.com", "192.168.1.1"]
blacklistFile = "./config/blacklist.json"

# ==================== 白名单配置 ====================
[whitelist]
# 是否启用白名单功能
# true: 启用，仅允许白名单中的域名或IP访问
# false: 禁用白名单功能
# 注意：启用白名单时，只有白名单中的地址才能被代理
enabled = false

# 白名单文件路径
# JSON格式文件，包含被允许访问的域名、IP地址等
# 文件格式示例：["github.com", "gitlab.com", "huggingface.co"]
whitelistFile = "./config/whitelist.json"

# ==================== 速率限制配置 ====================
[rateLimit]
# 是否启用速率限制功能
# true: 启用，限制客户端访问频率，防止滥用
# false: 禁用速率限制
enabled = false

# 每分钟允许的请求数量
# 超过此数量的请求将被暂时拒绝
# 可根据服务器性能和预期用户量调整
ratePerMinute = 180

# 突发请求允许的数量
# 允许短时间内的突发请求，但总体仍受ratePerMinute限制
# 提供更好的用户体验，避免偶发的请求被拒绝
burst = 5

# ==================== 带宽限制配置 ====================
[rateLimit.bandwidthLimit]
# 是否启用带宽限制功能
# true: 启用，限制总体和单个连接的带宽使用
# false: 禁用带宽限制
enabled = false

# 服务器总带宽限制
# 格式：数字+单位（如100mbps, 1gbps）
# 限制所有连接的总带宽使用量
totalLimit = "100mbps"

# 服务器总带宽突发限制
# 允许短时间内超过totalLimit的带宽使用
# 提供更好的下载体验
totalBurst = "100mbps"

# 单个连接带宽限制
# 限制每个客户端连接的最大带宽
# 防止单个用户占用过多带宽影响其他用户
singleLimit = "10mbps"

# 单个连接带宽突发限制
# 允许单个连接短时间内超过singleLimit
# 提高单个文件下载的体验
singleBurst = "10mbps"