version: '3.8'

services:
  ghproxy:
    image: vansour/ghproxy:latest
    container_name: ghproxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 日志持久化
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ghproxy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    # 安全配置
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50m
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

networks:
  ghproxy-network:
    driver: bridge
    name: ghproxy-network

volumes:
  ghproxy-logs:
    driver: local
